[package]
name = "ampctl"
edition.workspace = true
version.workspace = true
license-file.workspace = true
build = "build.rs"

[lib]
name = "ampctl"
path = "src/lib.rs"

[[bin]]
name = "ampctl"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
common = { path = "../../core/common" }
console = "0.16.1"
datasets-common = { path = "../../core/datasets-common" }
monitoring = { path = "../../core/monitoring" }
object_store.workspace = true
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true

[build-dependencies]
vergen-gitcl = { version = "1.0", features = ["build"] }
