[package]
name = "ampctl"
edition.workspace = true
version.workspace = true
license-file.workspace = true
build = "build.rs"

[lib]
name = "ampctl"
path = "src/lib.rs"

[[bin]]
name = "ampctl"
path = "src/main.rs"

[dependencies]
admin-client = { path = "../../clients/admin" }
amp-object-store = { path = "../../core/object-store" }
anyhow.workspace = true
async-trait.workspace = true
clap.workspace = true
common = { path = "../../core/common" }
console = "0.16.1"
datafusion.workspace = true
dataset-authoring = { path = "../../core/dataset-authoring" }
datasets-common = { path = "../../core/datasets-common" }
datasets-derived = { path = "../../core/datasets-derived" }
dump = { path = "../../core/dump" }
evm-rpc-datasets = { path = "../../extractors/evm-rpc" }
firehose-datasets = { path = "../../extractors/firehose" }
monitoring = { path = "../../core/monitoring" }
object_store.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
solana-datasets = { path = "../../extractors/solana" }
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
url.workspace = true
worker = { path = "../../services/worker" }

[build-dependencies]
vergen-gitcl = { version = "9.0.0", features = ["build"] }
