[package]
name = "ampctl"
edition.workspace = true
version.workspace = true
license-file.workspace = true
build = "build.rs"

[lib]
name = "ampctl"
path = "src/lib.rs"

[[bin]]
name = "ampctl"
path = "src/main.rs"

[dependencies]
admin-client = { path = "../../clients/admin" }
anyhow.workspace = true
clap.workspace = true
common = { path = "../../core/common" }
console = "0.16.1"
dataset-store = { path = "../../core/dataset-store" }
datasets-common = { path = "../../core/datasets-common" }
dump = { path = "../../core/dump" }
eth-beacon-datasets = { path = "../../extractors/eth-beacon" }
evm-rpc-datasets = { path = "../../extractors/evm-rpc" }
firehose-datasets = { path = "../../extractors/firehose" }
monitoring = { path = "../../core/monitoring" }
object_store.workspace = true
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde.workspace = true
serde_json.workspace = true
solana-datasets = { path = "../../extractors/solana" }
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
url.workspace = true
urlencoding = "2.1"
worker = { path = "../../services/worker" }

[build-dependencies]
vergen-gitcl = { version = "1.0.8", features = ["build"] }
