apiVersion: apps/v1
kind: Deployment
metadata:
  name: amp
spec:
  template:
    spec:
      containers:
        - name: controller
          image: ghcr.io/edgeandnode/amp:latest # This is just a placeholder, the image is set by the ArgoCD app
          command: ["/ampd", "controller"]
          ports:
            - containerPort: 1610
              name: admin
          env:
            - name: AMP_CONFIG_DATA_DIR
              valueFrom:
                secretKeyRef:
                  name: config-secrets-controller
                  key: data_dir
            - name: AMP_CONFIG_PROVIDERS_DIR
              valueFrom:
                secretKeyRef:
                  name: config-secrets-controller
                  key: providers_dir
            - name: AMP_CONFIG_DATASET_DEFS_DIR
              valueFrom:
                secretKeyRef:
                  name: config-secrets-controller
                  key: dataset_defs_dir
            - name: AMP_CONFIG_METADATA_DB_URL
              valueFrom:
                secretKeyRef:
                  name: config-secrets-controller
                  key: db_url
            - name: AMP_CONFIG
              value: /config/config.toml
