kind = "firehose"

# The name of the dataset. This will be used as the dataset directory name under the data directory,
# and also as the catalog schema name in the SQL interface.
name = "example_firehose"

# The network for this dataset. Must match the provider.
# Follow the 'CLI name' in this table:
# https://thegraph.com/docs/en/developing/supported-networks/
network = "mainnet"
