[package]
name = "http-common"
version.workspace = true
edition.workspace = true

[dependencies]
serde_json.workspace = true
axum.workspace = true
reqwest = "0.12.0"
common = { path = "../common" }
tokio.workspace = true