[package]
name = "ampup"
version.workspace = true
license-file.workspace = true
edition.workspace = true
build = "build.rs"

[lib]
name = "ampup"
path = "src/lib.rs"

[[bin]]
name = "ampup"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
console = "0.15"
dialoguer = "0.11"
fs-err.workspace = true
futures.workspace = true
indicatif = "0.17"
reqwest.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true

[build-dependencies]
vergen-gitcl = { version = "9.0.0", features = ["build"] }
