[package]
name = "ampup"
version.workspace = true
license-file.workspace = true
edition.workspace = true
build = "build.rs"

[lib]
name = "ampup"
path = "src/lib.rs"

[[bin]]
name = "ampup"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
fs-err.workspace = true
futures.workspace = true
reqwest.workspace = true
semver.workspace = true
serde.workspace = true
tempfile.workspace = true
tokio.workspace = true
indicatif = "0.17"
console = "0.15"
dialoguer = "0.11"

[build-dependencies]
vergen-gitcl = { version = "1.0.8", features = ["build"] }
