[package]
name = "worker"
edition = "2024"
version.workspace = true
license-file.workspace = true

[dependencies]
amp-data-store = { path = "../../core/data-store" }
backon.workspace = true
chrono.workspace = true
amp-config = { path = "../../config" }
amp-dataset-store = { path = "../../core/dataset-store" }
datasets-common = { path = "../../core/datasets-common" }
dump = { path = "../../core/dump" }
futures.workspace = true
metadata-db = { path = "../../core/metadata-db" }
monitoring = { path = "../../core/monitoring" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
