[package]
name = "worker"
edition = "2024"
version.workspace = true

[dependencies]
backon.workspace = true
common = { path = "../../core/common" }
dataset-store = { path = "../../core/dataset-store" }
dump = { path = "../../core/dump" }
futures.workspace = true
metadata-db = { path = "../../core/metadata-db" }
monitoring = { path = "../../core/monitoring" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
