[package]
name = "dump"
edition.workspace = true
version.workspace = true

[dependencies]
metadata-db = { path = "../metadata-db" }
common = { path = "../common" }
datafusion.workspace = true
dataset-store = { path = "../dataset-store" }
futures.workspace = true
tracing.workspace = true
object_store.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
url.workspace = true
serde_json.workspace = true
serde.workspace = true
backon.workspace = true
rand.workspace = true
tokio-util.workspace = true
alloy.workspace = true
monitoring = { path = "../monitoring" }
