[package]
name = "dump"
edition.workspace = true
version.workspace = true
license-file.workspace = true

[dependencies]
alloy.workspace = true
amp-data-store = { path = "../data-store" }
amp-dataset-store = { path = "../dataset-store" }
async-stream.workspace = true
common = { path = "../common" }
datafusion.workspace = true
datasets-common = { path = "../datasets-common" }
datasets-derived = { path = "../datasets-derived" }
futures.workspace = true
metadata-db = { path = "../metadata-db" }
monitoring = { path = "../monitoring" }
object_store.workspace = true
parking_lot = "0.12.5"
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tracing.workspace = true
url.workspace = true
