[package]
name = "nozzleup"
version = "1.0.0"
edition.workspace = true

[lib]
name = "nozzleup"
path = "src/lib.rs"

[[bin]]
name = "nozzleup"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
fs-err.workspace = true
futures.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio.workspace = true
url.workspace = true

# Additional dependencies for nozzleup
indicatif = "0.17"
console = "0.15"
dialoguer = "0.11"

[dev-dependencies]
pretty_assertions.workspace = true
