[package]
name = "eth-beacon-datasets"
edition.workspace = true
version.workspace = true
license-file.workspace = true

[features]
schemars = ["dep:schemars", "datasets-common/schemars", "dep:serde_json"]

[dependencies]
alloy.workspace = true
async-stream.workspace = true
common = { path = "../../core/common" }
datasets-common = { path = "../../core/datasets-common" }
futures.workspace = true
governor.workspace = true
reqwest.workspace = true
schemars = { workspace = true, optional = true }
serde.workspace = true
serde_json = { workspace = true, optional = true }
serde_with = "3.14.0"
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
fs-err.workspace = true
serde_json.workspace = true
