[package]
name = "eth-beacon-datasets"
edition.workspace = true
version.workspace = true

[dependencies]
alloy.workspace = true
async-stream.workspace = true
common = { path = "../../core/common" }
futures.workspace = true
governor.workspace = true
reqwest.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with = "3.14.0"
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true

[dev-dependencies]
fs-err.workspace = true
serde_json.workspace = true
