[package]
name = "ampsync"
description = "Syncing engine that listens to the stream changes from the nozzle-client streaming layer to store changes in a configured database."
edition.workspace = true
version.workspace = true

[features]
# Default features (enabled by default)
default = ["snmalloc"]
# Enable snmalloc memory allocator for improved performance
snmalloc = ["dep:snmalloc-rs"]

[dependencies]
backon.workspace = true
bytes = "1.10.1"
common = { path = "../../core/common" }
datafusion.workspace = true
futures.workspace = true
monitoring = { path = "../../core/monitoring" }
nozzle-client = { path = "../../client" }
oxc_allocator = "0.93"
oxc_ast = "0.93"
oxc_ast_visit = "0.93"
oxc_parser = "0.93"
oxc_span = "0.93"
serde_json.workspace = true
snmalloc-rs = { version = "0.3.4", optional = true }
sqlx = { version = "0.8.6", features = [
    "runtime-tokio",
    "postgres",
    "migrate",
    "macros",
    "chrono",
] }
pgpq = { git = "https://github.com/adriangb/pgpq.git" }
thiserror.workspace = true
tokio = { workspace = true, features = ["signal"] }
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true