[workspace]
members = [
    "firehose-datasets",
    "common",
    "dump",
    "server",
    "dump-check",
    "substreams-datasets",
    "evm-rpc-datasets",
]

resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
tokio = { version = "1.36.0", features = [
    "macros",
    "test-util",
    "rt-multi-thread",
    "parking_lot",
] }
tonic = { version = "0.11.0", features = [
    "transport",
    "gzip",
    "prost",
    "tls-roots",
] }
tonic-build = "0.11"
prost = "0.12"
prost-types = "0.12"
prost-build = "0.12"
thiserror = "1.0"
futures = "0.3"
hex = "0.4.3"
serde = { version = "1.0.197", features = ["derive"] }
serde_derive = "1.0.197"
clap = { version = "4.5.2", features = ["derive", "env"] }
toml = "0.8.10"
fs-err = "2.11.0"
serde_json = "1.0.114"
url = "2.5.0"
async-trait = "0.1.80"
bytes = "1"
lazy_static = "1.4.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
log = "0.4"
alloy-core = { version = "0.7.2", features = ["std", "json-abi", "dyn-abi"] }
itertools = "0.12.1"
atty = "0.2.14"
snmalloc-rs = "0.3.4"
prometheus = "0.13"

# Datafusion and Arrow crates
datafusion = "38"
datafusion-proto = "38"
object_store = { version = "0.9.1", features = ["aws", "gcp"] }
