[workspace]
members = ["firehose-datasources", "common", "dump"]

resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
tokio = { version = "1.36.0", features = [
    "macros",
    "test-util",
    "rt-multi-thread",
    "parking_lot",
] }
tonic = { version = "0.11.0", features = ["gzip", "prost", "tls-roots"] }
tonic-build = "0.11"
prost = "0.12"
prost-types = "0.12"
prost-build = "0.12"
thiserror = "1.0"
futures = "0.3"
hex = "0.4.3"
serde = { version = "1.0.197", features = ["derive"] }
serde_derive = "1.0.197"
clap = { version = "4.5.2", features = ["derive", "env"] }
toml = "0.8.10"
anyhow = "1.0.80"
fs-err = "2.11.0"
serde_json = "1.0.114"

# Switch to datafusion v37 when it's released, in about a week.
datafusion = { git = "https://github.com/apache/arrow-datafusion.git" }
object_store = "0.9.1"
