[workspace]
members = ["firehose-datasources", "common"]

resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
tokio = { version = "1.36.0", features = [
    "macros",
    "test-util",
    "rt-multi-thread",
    "parking_lot",
] }
tonic = { version = "0.11.0", features = ["gzip", "prost", "tls-roots"] }
tonic-build = "0.11"
prost = "0.12"
prost-types = "0.12"
thiserror = "1.0"
futures = "0.3"
hex = "0.4.3"
serde = "1.0.197"
serde_derive = "1.0.197"
clap = { version = "4.5.2", features = ["derive", "env"] }
toml = "0.8.10"
anyhow = "1.0.80"
fs-err = "2.11.0"
serde_json = "1.0.114"

# When bumping the `datafusion` version, you may get an error involving `serde_arrow`. This means
# `datafusion` bumped arrow and the `serde_arrow` feature needs to be updated to match.
datafusion = "36.0.0"
serde_arrow = { version = "0.10.0", features = ["arrow-50"] }
