[workspace]
members = [
    "nozzle",
    "server",
    "dump",
    "dump-check",
    "tests",
    "common",
    "dataset-store",
    "evm-rpc-datasets",
    "firehose-datasets",
    "substreams-datasets",
    "metadata-db",
    "admin-api",
    "http-common",
    "registry-service",
]

resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
alloy = { version = "0.6.2", features = [
    "json-abi",
    "dyn-abi",
    "provider-http",
    "rpc-types",
] }
async-trait = "0.1.80"
atty = "0.2.14"
bytes = "1"
clap = { version = "4.5.2", features = ["derive", "env"] }
figment = { version = "0.10.19", features = ["toml", "env", "json"] }
fs-err = "2.11.0"
futures = "0.3"
hex = "0.4.3"
itertools = "0.13.0"
log = "0.4"
pretty_assertions = "1.4.1"
prometheus = "0.13"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
snmalloc-rs = "0.3.4"
tempfile = "3.13.0"
thiserror = "1.0"
toml = "0.8.10"
tracing = "0.1"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tokio = { version = "1.36.0", features = [
    "macros",
    "test-util",
    "rt-multi-thread",
    "parking_lot",
] }
url = "2.5.0"
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "postgres",
    "migrate",
    "macros",
] }
uuid = { version = "1.11.0", features = ["v7"] }
axum = "0.8.0"
semver = { version = "1.0.18", features = ["serde"] }
rand = "0.8.5"

# Datafusion and Arrow crates
arrow-flight = { version = "53.3", features = ["flight-sql-experimental"] }
datafusion = { version = "44", features = ["serde"] }
datafusion-proto = "44"
object_store = { version = "0.11.2", features = ["aws", "gcp", "azure"] }

# Crates that should follow the version used by DataFusion and Arrow
prost = "0.13.3"
prost-build = "0.13.3"
tonic = { version = "0.12.3", features = ["transport", "gzip", "tls-roots"] }
tonic-build = "0.12.3"

# Prost fork
#
# The only change in our fork is to bump the recursion limit from 100 to 1000, to allow deserializing
# larger queries serialized with datafusion-proto. This is preferable to using the
# `no-recursion-limit` feature, for two reasons:
# 1. It's more secure, as it still prevents stack overflow attacks, just with a larger limit.
# 2. `no-recursion-limit` did not work, in our testing it work on macos but not on linux.
#
# Something like https://github.com/tokio-rs/prost/pull/785 would enable us to remove this fork.
[patch.crates-io]
prost = { git = "https://github.com/edgeandnode/prost", branch = "nozzle-fork-0.13.3" }
