[package]
name = "admin-api"
version.workspace = true
license-file.workspace = true
edition.workspace = true

[dependencies]
axum.workspace = true
common = { path = "../../core/common" }
dataset-store = { path = "../../core/dataset-store" }
datasets-common = { path = "../../core/datasets-common" }
datasets-derived = { path = "../../core/datasets-derived" }
dump = { path = "../../core/dump" }
evm-rpc-datasets = { path = "../../extractors/evm-rpc" }
futures.workspace = true
metadata-db = { path = "../../core/metadata-db" }
monitoring = { path = "../../core/monitoring" }
object_store.workspace = true
opentelemetry-instrumentation-tower = { version = "0.17", features = ["axum"] }
tokio.workspace = true
tower-http = { workspace = true, features = ["cors"] }
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with = "3.14.0"
thiserror.workspace = true
toml.workspace = true
tracing.workspace = true
utoipa = { version = "5.4.0", features = ["axum_extras"], optional = true }
worker = { path = "../worker" }
