kind = "substreams"

name = "example_substreams"

# Path to the provider relative to the provider directory.
provider = "provider_example.toml"

# Substreams output module name
module = "map_events"

# Substreams package manifest URL
manifest = "https://spkg.io/<package>"
