[package]
name = "firehose-datasets"
edition.workspace = true

[[example]]
name = "dump"

[dependencies]
types = { path = "../types" }
tonic.workspace = true
prost.workspace = true
prost-types.workspace = true
thiserror.workspace = true
futures.workspace = true
hex.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_arrow.workspace = true
clap.workspace = true
toml.workspace = true
anyhow.workspace = true

[build-dependencies]
tonic-build.workspace = true

[dev-dependencies]
prost-reflect = "0.13.0"
tokio.workspace = true
fs-err.workspace = true
serde_json.workspace = true
