[package]
name = "ampq"
edition.workspace = true
version.workspace = true
license-file.workspace = true

[dependencies]
amp-client = { version = "0.1.0", path = "../../client", features = ["lmdb"] }
anyhow.workspace = true
chrono.workspace = true
clap = { workspace = true, features = ["derive"] }
common = { version = "0.1.0", path = "../../core/common" }
crossterm = "0.29.0"
futures.workspace = true
hex.workspace = true
ratatui = "0.29.0"
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
