[package]
name = "substreams-datasets"
edition.workspace = true
version.workspace = true

[features]
# Enable protobuf code generation during build process. When enabled, the build script
# will generate Rust bindings from .proto files using prost and tonic for Substreams protocol support
gen-proto = ["dep:prost-build", "dep:tonic-build"]

[dependencies]
anyhow.workspace = true
async-stream.workspace = true
chrono.workspace = true
common = { path = "../../core/common" }
firehose-datasets = { path = "../firehose" }
schemars.workspace = true
futures.workspace = true
tracing.workspace = true
prost-reflect = "0.15.0"
prost.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
toml.workspace = true
tonic.workspace = true
datafusion.workspace = true

[build-dependencies]
prost-build = { workspace = true, optional = true }
tonic-build = { workspace = true, optional = true }

[dev-dependencies]
serde_json.workspace = true
tokio.workspace = true
