[package]
name = "json-schema-derive"
edition.workspace = true
version.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2", features = ["full"] }
proc-macro2 = "1.0"
regex = "1"
tokio.workspace = true
serde_json.workspace = true
