[package]
name = "config"
edition.workspace = true
version.workspace = true
license-file.workspace = true

[dependencies]
amp-object-store = { path = "../core/object-store" }
common = { path = "../core/common" }
datafusion.workspace = true
dump = { path = "../core/dump" }
figment.workspace = true
fs-err.workspace = true
metadata-db = { path = "../core/metadata-db" }
metadata-db-postgres = { path = "../services/metadata-db-postgres" }
monitoring = { path = "../core/monitoring" }
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt"] }
