[package]
name = "datasets-raw"
edition.workspace = true
version.workspace = true
license-file.workspace = true

[features]
gen-schema = ["dep:datafusion"]

[dependencies]
# Always available - provides Table type
datasets-common = { path = "../datasets-common" }

# For BlockStreamer and RawBlockRange
arrow = { workspace = true }
async-stream = { workspace = true }
backon = { workspace = true }
futures = { workspace = true }
monitoring = { path = "../monitoring" }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

# Only for schema generation
datafusion = { workspace = true, optional = true }
