[package]
name = "datasets-raw"
edition.workspace = true
version.workspace = true
license-file.workspace = true

[features]
gen-schema = ["dep:datafusion", "dep:tokio"]

[dependencies]
# Always available - provides Table type
common = { path = "../common" }

# Only for schema generation
datafusion = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
