apiVersion: v1
kind: Service
metadata:
  name: amp-controller
  annotations:
    cloud.google.com/l4-rbs: "enabled"
spec:
  type: ClusterIP
  ports:
    - name: admin
      protocol: TCP
      port: 1610
      targetPort: admin
