[package]
name = "metadata-db"
edition.workspace = true
version.workspace = true
license-file.workspace = true

[features]
# Default features (enabled by default)
default = []
# Temporary database support for testing environments
temp-db = ["pgtemp"]

[dependencies]
backon.workspace = true
futures.workspace = true
hex.workspace = true
indoc.workspace = true
pgtemp = { version = "0.6.0", optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sqlx = { version = "0.8.3", features = [
    "runtime-tokio",
    "postgres",
    "migrate",
    "macros",
    "chrono",
] }
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
pgtemp = "0.6.0"
tokio = { workspace = true, features = ["macros", "test-util"] }
