[package]
name = "metadata-db"
edition.workspace = true
version.workspace = true

[features]
default = []
temp-db = ["pgtemp", "backon"]

[dependencies]
pgtemp = { version = "0.6.0", optional = true }
sqlx = { version = "0.8.3", features = [
    "runtime-tokio",
    "postgres",
    "migrate",
    "macros",
    "chrono",
] }
thiserror.workspace = true
url.workspace = true
tracing.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
futures.workspace = true
tokio.workspace = true
indoc.workspace = true
backon = { workspace = true, optional = true }

[dev-dependencies]
pgtemp = "0.6.0"
tokio = { workspace = true, features = ["macros", "test-util"] }
metadata-db = { path = ".", features = ["temp-db"] }
