[package]
name = "metadata-db"
edition.workspace = true
version.workspace = true
license-file.workspace = true

[features]
# Default features (enabled by default)
default = []
# Temporary database support for testing environments
temp-db = ["pgtemp", "backon"]

[dependencies]
backon = { workspace = true, optional = true }
futures.workspace = true
indoc.workspace = true
pgtemp = { version = "0.6.0", optional = true }
semver.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sqlx = { version = "0.8.3", features = [
    "runtime-tokio",
    "postgres",
    "migrate",
    "macros",
    "chrono",
] }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
metadata-db = { path = ".", features = ["temp-db"] }
pgtemp = "0.6.0"
rand.workspace = true
tokio = { workspace = true, features = ["macros", "test-util"] }
