[package]
name = "js-runtime"
edition.workspace = true
version.workspace = true
license-file.workspace = true

[dependencies]
async-trait.workspace = true
blake3.workspace = true
datafusion.workspace = true
deadpool = "0.12.2"
lru = "0.16.3"
num-traits = "0.2.19"
num_cpus = "1.16.0"
thiserror.workspace = true
tokio.workspace = true
v8 = "135.1.0"

[dev-dependencies]
hex.workspace = true
indoc.workspace = true
