[package]
name = "js-runtime"
edition.workspace = true
version.workspace = true
license-file.workspace = true

[dependencies]
v8 = "135.1.0"
datafusion.workspace = true
thiserror.workspace = true
blake3.workspace = true
num-traits = "0.2.19"
deadpool = "0.12.2"
num_cpus = "1.16.0"
tokio.workspace = true

[dev-dependencies]
hex.workspace = true
