[package]
name = "dataset-store"
edition.workspace = true
version.workspace = true

[dependencies]
common = { path = "../common" }
firehose-datasets = { path = "../firehose-datasets" }
substreams-datasets = { path = "../substreams-datasets" }
tokio.workspace = true
toml.workspace = true
thiserror.workspace = true
object_store.workspace = true
datafusion.workspace = true
