[package]
name = "http-common"
version.workspace = true
license-file.workspace = true
edition.workspace = true

[dependencies]
serde_json.workspace = true
axum.workspace = true
common = { path = "../../core/common" }
tokio.workspace = true
tower-http = { version = "0.6.2", features = ["cors"] }
