[package]
name = "dump"
edition.workspace = true
version.workspace = true

[dependencies]
common = { path = "../common" }
firehose-datasets = { path = "../firehose-datasets" }
substreams-datasets = { path = "../substreams-datasets" }
tokio.workspace = true
serde_json.workspace = true
futures.workspace = true
clap.workspace = true
object_store.workspace = true
fs-err.workspace = true
toml.workspace = true
url.workspace = true
log.workspace = true
datafusion.workspace = true
snmalloc-rs.workspace = true
prometheus.workspace = true
