[package]
name = "dataset-authoring"
edition.workspace = true
version.workspace = true
license-file.workspace = true

[dependencies]
async-trait.workspace = true
common = { path = "../common" }
datafusion.workspace = true
datasets-common = { path = "../datasets-common" }
dirs.workspace = true
datasets-derived = { path = "../datasets-derived" }
flate2.workspace = true
minijinja.workspace = true
serde_json_canonicalizer.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
semver.workspace = true
tar.workspace = true
thiserror.workspace = true
walkdir.workspace = true

[dev-dependencies]
regex.workspace = true
tempfile.workspace = true
tokio.workspace = true
