[package]
name = "ampup-gen-release-manifest"
version.workspace = true
license-file.workspace = true
edition.workspace = true

[[bin]]
name = "ampup-gen-release-manifest"
path = "src/main.rs"

[dependencies]
ampup = { path = "../ampup" }
chrono.workspace = true
clap.workspace = true
reqwest.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
