[package]
name = "monitoring"
edition.workspace = true
version.workspace = true
license-file.workspace = true

[dependencies]
common = { path = "../common" }
datafusion.workspace = true
opentelemetry.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry_sdk.workspace = true
tokio.workspace = true
tokio-metrics.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true


[dev-dependencies]
cargo_metadata = "0.19.0"
