[package]
name = "monitoring"
edition.workspace = true
version.workspace = true

[dependencies]
common = { path = "../common" }
metadata-db = { path = "../metadata-db" }
opentelemetry.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry_sdk.workspace = true
tracing.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true


[dev-dependencies]
cargo_metadata = "0.19.0"
