[package]
name = "ampcc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
crossterm = "0.27.0"
ratatui = "0.26.1"
tokio = { version = "1.36.0", features = ["full"] }
admin-client = { path = "../../admin-client" }
serde = { version = "1.0", features = ["derive"] }
figment = { version = "0.10", features = ["toml", "env"] }
directories = "5.0"
url.workspace = true
datasets-common = { path = "../../core/datasets-common" }
serde_json.workspace = true
reqwest.workspace = true
thiserror = "1.0"
urlencoding = "2.1"
