[package]
name = "ampcc"
description = "TUI to interact with Amp Datasets. View published Datasets, fetch and view their manifest and schemas. Search for Datasets."
edition.workspace = true
version.workspace = true
license-file.workspace = true

[dependencies]
amp-datasets-derived = { path = "../../core/datasets-derived", package = "datasets-derived", features = ["schemars"] }
amp-datasets-evmrpc = { path = "../../extractors/evm-rpc", package = "evm-rpc-datasets", features = ["schemars"] }
amp-datasets-firehose = { path = "../../extractors/firehose", package = "firehose-datasets", features = ["schemars"] }
alloy.workspace = true
anyhow.workspace = true
arboard = "3.6.1"
base64 = "0.22.1"
chrono.workspace = true
crossterm = "0.29.0"
dirs = "6.0.0"
open = "5.3.3"
rand = "0.9.2"
ratatui = "0.30"
sha2 = "0.10.9"
tokio.workspace = true
admin-client = { path = "../../clients/admin" }
worker = { path = "../../services/worker" }
schemars.workspace = true
serde.workspace = true
figment.workspace = true
directories = "6.0"
url.workspace = true
datasets-common = { path = "../../core/datasets-common" }
serde_json.workspace = true
reqwest.workspace = true
thiserror.workspace = true
urlencoding = "2.1"
