[package]
name = "server"
edition.workspace = true
version.workspace = true

[lib]
name = "server"

[[bin]]
name = "server"

[dependencies]
common = { path = "../common" }
firehose-datasets = { path = "../firehose-datasets" }
dataset-store = { path = "../dataset-store" }
arrow-flight.workspace = true
datafusion-proto.workspace = true
tonic.workspace = true
async-trait.workspace = true
futures.workspace = true
bytes.workspace = true
prost.workspace = true
thiserror.workspace = true
datafusion.workspace = true
tokio.workspace = true
log.workspace = true
snmalloc-rs.workspace = true
