[package]
name = "server"
edition.workspace = true
version.workspace = true

[dependencies]
common = { path = "../common" }
firehose-datasets = { path = "../firehose-datasets" }
arrow-flight = { version = "51.0.0", features = ["flight-sql-experimental"] }
datafusion-proto.workspace = true
tonic.workspace = true
async-trait.workspace = true
futures.workspace = true
bytes.workspace = true
prost.workspace = true
thiserror.workspace = true
datafusion.workspace = true
tokio.workspace = true
anyhow.workspace = true
log.workspace = true
snmalloc-rs.workspace = true
