[package]
name = "amp-worker-core"
edition.workspace = true
version.workspace = true
license-file.workspace = true

[features]
# JSON Schema generation support for configuration validation
schemars = ["dep:schemars", "common/schemars"]

[dependencies]
amp-data-store = { path = "../data-store" }
common = { path = "../common" }
datafusion.workspace = true
datasets-common = { path = "../datasets-common" }
futures.workspace = true
metadata-db = { path = "../metadata-db" }
monitoring = { path = "../monitoring" }
object_store.workspace = true
parking_lot.workspace = true
schemars = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
parquet-ext = { path = "../../parquet-ext", features = ["async", "zstd"] }

[dev-dependencies]
opentelemetry.workspace = true
