[package]
name = "amp-dataset-store"
edition.workspace = true
version.workspace = true
license-file.workspace = true


[dependencies]
async-stream.workspace = true
amp-datasets-registry = { path = "../datasets-registry" }
amp-providers-registry = { path = "../providers-registry" }
common = { path = "../common" }
datafusion.workspace = true
datasets-common = { path = "../datasets-common" }
datasets-derived = { path = "../datasets-derived" }
datasets-raw = { path = "../datasets-raw" }
evm-rpc-datasets = { path = "../../extractors/evm-rpc" }
firehose-datasets = { path = "../../extractors/firehose" }
futures.workspace = true
metadata-db = { path = "../metadata-db" }
monitoring = { path = "../monitoring" }
parking_lot = "0.12.4"
rand.workspace = true
serde.workspace = true
solana-datasets = { path = "../../extractors/solana" }
thiserror.workspace = true
toml = { workspace = true, features = ["preserve_order"] }
tracing.workspace = true
url.workspace = true
