[package]
name = "dataset-store"
edition.workspace = true
version.workspace = true


[dependencies]
async-stream.workspace = true
common = { path = "../common" }
datafusion.workspace = true
datasets-common = { path = "../datasets-common" }
datasets-derived = { version = "0.1.0", path = "../datasets-derived" }
eth-beacon-datasets = { version = "0.1.0", path = "../../extractors/eth-beacon" }
evm-rpc-datasets = { path = "../../extractors/evm-rpc" }
firehose-datasets = { path = "../../extractors/firehose" }
futures.workspace = true
js-runtime = { path = "../js-runtime" }
metadata-db = { path = "../metadata-db" }
monitoring = { path = "../monitoring" }
object_store.workspace = true
parking_lot = "0.12.4"
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
substreams-datasets = { path = "../../extractors/substreams" }
thiserror.workspace = true
tokio.workspace = true
toml = { workspace = true, features = ["preserve_order"] }
tracing.workspace = true
url.workspace = true

[dev-dependencies]
indoc.workspace = true
tokio = { workspace = true, features = ["macros"] }
