[package]
name = "dataset-store"
edition.workspace = true
version.workspace = true


[dependencies]
async-stream.workspace = true
metadata-db = { path = "../metadata-db" }
common = { path = "../common" }
js-runtime = { path = "../js-runtime" }
evm-rpc-datasets = { path = "../../extractors/evm-rpc" }
firehose-datasets = { path = "../../extractors/firehose" }
substreams-datasets = { path = "../../extractors/substreams" }
toml = { workspace = true, features = ["preserve_order"] }
thiserror.workspace = true
object_store.workspace = true
datafusion.workspace = true
serde.workspace = true
futures.workspace = true
serde_json.workspace = true
tracing.workspace = true
url.workspace = true
rand.workspace = true
parking_lot = "0.12.4"

[dev-dependencies]
indoc.workspace = true
tokio = { workspace = true, features = ["macros"] }
