[package]
name = "amp-worker-datasets-raw"
edition.workspace = true
version.workspace = true
license-file.workspace = true

[dependencies]
amp-data-store = { path = "../data-store" }
common = { path = "../common" }
datasets-common = { path = "../datasets-common" }
datasets-raw = { path = "../datasets-raw" }
amp-worker-core = { path = "../worker-core" }
futures.workspace = true
metadata-db = { path = "../metadata-db" }
monitoring = { path = "../monitoring" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tracing-subscriber = { workspace = true, features = ["env-filter"] }
