[package]
name = "generate-manifest"
edition.workspace = true
version.workspace = true

[dependencies]
common = { path = "../../core/common" }
dataset-store = { path = "../../core/dataset-store" }
evm-rpc-datasets = { path = "../../extractors/evm-rpc" }
firehose-datasets = { path = "../../extractors/firehose" }
substreams-datasets = { path = "../../extractors/substreams" }
serde_json.workspace = true
