[package]
name = "datasets-common"
edition.workspace = true
version.workspace = true
license-file.workspace = true

[dependencies]
datafusion = { workspace = true }
metadata-db = { path = "../metadata-db" }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
semver = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
serde_json.workspace = true
