[package]
name = "datasets-common"
edition.workspace = true
version.workspace = true

[features]
schemars = ["dep:schemars"]

[dependencies]
datafusion = { workspace = true }
metadata-db = { path = "../metadata-db" }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
semver = { workspace = true }
thiserror = { workspace = true }
