[package]
name = "datasets-common"
edition.workspace = true
version.workspace = true
license-file.workspace = true


[features]
default = ["metadata-db"]

[dependencies]
datafusion = { workspace = true }
hex = { workspace = true }
metadata-db = { path = "../metadata-db", optional = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
semver = { workspace = true }
sha2 = "0.10"
thiserror = { workspace = true }
js-runtime = { path = "../js-runtime" }

[dev-dependencies]
serde_json.workspace = true
