apiVersion: apps/v1
kind: Deployment
metadata:
  name: amp
spec:
  template:
    spec:
      containers:
        - name: gateway
          image: envoyproxy/envoy:v1.28-latest # This is just a placeholder, the image is set by the ArgoCD app
          command: ["/usr/local/bin/envoy", "-c", "/config/envoy-config.yaml"]
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: amp-envoy-config
              mountPath: "/config"
      volumes:
        - name: amp-envoy-config
          configMap:
            name: amp-envoy-config-gateway
            items:
              - key: envoy-config.yaml
                path: envoy-config.yaml
