[package]
name = "metadata-db"
edition.workspace = true
version.workspace = true

[dependencies]
pgtemp = "0.6.0"
sqlx.workspace = true
thiserror.workspace = true
url.workspace = true
tracing.workspace = true
serde_json.workspace = true
futures.workspace = true
tokio.workspace = true
