[package]
name = "metadata-db"
edition.workspace = true
version.workspace = true

[dependencies]
sqlx.workspace = true
thiserror.workspace = true
uuid.workspace = true
url.workspace = true
tracing.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true