[package]
name = "metadata-db-postgres"
version.workspace = true
license-file.workspace = true
edition.workspace = true

[dependencies]
backon.workspace = true
fs-err = { workspace = true, features = ["tokio"] }
nix = { workspace = true, features = ["signal"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "io-util", "net", "process", "signal", "sync", "time"] }
tracing.workspace = true
which.workspace = true
