apiVersion: apps/v1
kind: Deployment
metadata:
  name: amp-server
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    spec:
      imagePullSecrets:
        - name: docker-registry
      containers:
        - name: amp-server
          image: AMP_SERVER_IMAGE_NAME
          command: ["/ampd", "server"]
          ports:
            - name: flight
              containerPort: 1602
            - name: jsonl
              containerPort: 1603
            - name: registry
              containerPort: 1611
          env:
            - name: AMP_CONFIG_DATA_DIR
              valueFrom:
                secretKeyRef:
                  name: amp-server-config-secrets
                  key: data_dir
            - name: AMP_CONFIG_PROVIDERS_DIR
              valueFrom:
                secretKeyRef:
                  name: amp-server-config-secrets
                  key: providers_dir
            - name: AMP_CONFIG_DATASET_DEFS_DIR
              valueFrom:
                secretKeyRef:
                  name: amp-server-config-secrets
                  key: dataset_defs_dir
            - name: AMP_CONFIG_METADATA_DB_URL
              valueFrom:
                secretKeyRef:
                  name: amp-server-config-secrets
                  key: db_url
            - name: AMP_CONFIG
              value: /config/config.toml
            - name: RUST_BACKTRACE
              value: "1"
          volumeMounts:
            - name: amp-server-config
              mountPath: /config
      volumes:
        - name: amp-server-config
          configMap:
            name: amp-server-config
            items:
              - key: config.toml
                path: config.toml
