apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/l4-rbs: "enabled"
  name: amp-server
spec:
  type: ClusterIP
  ports:
    - name: grpc
      protocol: TCP
      port: 80
      targetPort: flight
    - name: json-lines
      protocol: TCP
      port: 1603
      targetPort: jsonl
    - name: registry
      protocol: TCP
      port: 1611
      targetPort: registry
