[package]
name = "datasets-derived"
edition = "2024"
version.workspace = true
license-file.workspace = true

[features]
schemars = ["dep:schemars", "datasets-common/schemars", "dep:serde_json"]

[dependencies]
datasets-common = { path = "../datasets-common" }
schemars = { workspace = true, optional = true }
serde.workspace = true
serde_json = {workspace = true, optional = true}
thiserror.workspace = true

