[package]
name = "datasets-derived"
edition = "2024"
version.workspace = true
license-file.workspace = true

[features]
schemars = ["dep:schemars", "datasets-common/schemars", "common/schemars", "dep:serde_json"]

[dependencies]
common = { version = "0.1.0", path = "../common" }
datafusion.workspace = true
datasets-common = { path = "../datasets-common" }
js-runtime = { version = "0.1.0", path = "../js-runtime" }
metadata-db = { version = "0.1.0", path = "../metadata-db" }
schemars = { workspace = true, optional = true }
serde.workspace = true
serde_json = {workspace = true, optional = true}
thiserror.workspace = true
tracing.workspace = true

