[package]
name = "controller"
edition = "2024"
version.workspace = true
license-file.workspace = true

[dependencies]
admin-api = { path = "../admin-api" }
common = { path = "../../core/common" }
monitoring = { path = "../../core/monitoring" }
