[package]
name = "server"
edition.workspace = true
version.workspace = true
license-file.workspace = true

[dependencies]
arrow-flight.workspace = true
async-stream.workspace = true
async-trait.workspace = true
axum.workspace = true
bytes.workspace = true
common = { path = "../../core/common" }
datafusion.workspace = true
dataset-store = { path = "../../core/dataset-store" }
dump = { path = "../../core/dump" }
futures.workspace = true
metadata-db = { path = "../../core/metadata-db" }
monitoring = { path = "../../core/monitoring" }
prost.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tonic.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio.workspace = true
