[package]
name = "server"
edition.workspace = true
version.workspace = true
license-file.workspace = true

[dependencies]
amp-data-store = { path = "../../core/data-store" }
arrow-flight.workspace = true
async-stream.workspace = true
async-trait.workspace = true
axum.workspace = true
bincode.workspace = true
bytes.workspace = true
common = { path = "../../core/common" }
datafusion.workspace = true
datasets-common = { path = "../../core/datasets-common", features = ["bincode"] }
amp-dataset-store = { path = "../../core/dataset-store" }
dump = { path = "../../core/dump" }
futures.workspace = true
js-runtime = { path = "../../core/js-runtime" }
metadata-db = { path = "../../core/metadata-db" }
monitoring = { path = "../../core/monitoring" }
prost.workspace = true
rand.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["net"] }
tonic.workspace = true
tower-http = { version = "0.6.2", features = ["compression-gzip", "cors"] }
tracing.workspace = true
