# The network for this endpoint. Follow the 'CLI name' in this table:
# https://thegraph.com/docs/en/developing/supported-networks/
network = "mainnet"

# The EVM RPC endpoint
url = "https://<ENDPOINT>"

# Rpc batch size, defaults to 100 if not set.
# The maximum number of requests to send in a single batch. When set to 1, no batching is used.
rpc_batch_size = 100
