[package]
name = "common"
edition.workspace = true
version.workspace = true

[dependencies]
alloy.workspace = true
atty.workspace = true
bytes.workspace = true
datafusion-proto.workspace = true
datafusion.workspace = true
figment.workspace = true
fs-err.workspace = true
futures.workspace = true
itertools.workspace = true
log.workspace = true
object_store.workspace = true
serde.workspace = true
stable-hash = { git = "https://github.com/graphprotocol/stable-hash" }
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
tracing-subscriber.workspace = true
url.workspace = true

[dev-dependencies]
rand = "0.8.5"
