[package]
name = "common"
edition.workspace = true
version.workspace = true

[dependencies]
datafusion.workspace = true
url.workspace = true
anyhow.workspace = true
object_store.workspace = true
datafusion-proto.workspace = true
thiserror.workspace = true
tokio.workspace = true
futures.workspace = true
lazy_static.workspace = true
serde.workspace = true
toml.workspace = true
