apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: amp-gateway
  labels:
    app: amp-gateway
spec:
  selector:
    matchLabels:
      app: amp-gateway
  endpoints:
    - port: metrics
