apiVersion: v1
kind: Service
metadata:
  name: amp-gateway
  annotations:
    cloud.google.com/l4-rbs: "enabled"
spec:
  type: ClusterIP
  selector:
    app: amp-gateway
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
