[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["contracts/lib"]
test = "contracts/test"
script = "contracts/script"
cache_path = "contracts/cache"
via_ir = true
optimizer = true
optimizer_runs = 200

[lint]
ignore = [
    "contracts/src/*Verifier.sol",
]

[fmt]
ignore = [
    "contracts/src/*Verifier.sol",
]
