[package]
name = "canton-scan-datasets"
edition.workspace = true
version.workspace = true
license-file.workspace = true

[features]
schemars = ["dep:schemars", "datasets-common/schemars"]

[dependencies]
alloy.workspace = true
arrow.workspace = true
async-stream.workspace = true
chrono.workspace = true
csv = "1.3"
datasets-common = { path = "../../core/datasets-common" }
datasets-raw = { path = "../../core/datasets-raw" }
flate2 = "1.0"
futures.workspace = true
reqwest.workspace = true
schemars = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
serde_with = "3.9.0"
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
tempfile = "3"
