[package]
name = "nozzle"
edition.workspace = true
version.workspace = true

[dependencies]
metadata-db = { path = "../metadata-db" }
arrow-flight.workspace = true
clap.workspace = true
common = { path = "../common" }
datafusion.workspace = true
dataset-store = { path = "../dataset-store" }
dump = { path = "../dump" }
log.workspace = true
server = { path = "../server" }
snmalloc-rs.workspace = true
tokio.workspace = true
tonic.workspace = true
