[package]
name = "nozzle"
edition.workspace = true
version.workspace = true

[dependencies]
alloy.workspace = true
anyhow = "1.0.95"
arrow-flight.workspace = true
arrow-json = "53.3.0"
axum.workspace = true
clap.workspace = true
common = { path = "../common" }
datafusion.workspace = true
dataset-store = { path = "../dataset-store" }
dump = { path = "../dump" }
futures.workspace = true
indoc = "2.0.5"
log.workspace = true
metadata-db = { path = "../metadata-db" }
server = { path = "../server" }
snmalloc-rs.workspace = true
tokio.workspace = true
tonic.workspace = true
tower-http = { version = "0.6.2", features = [
  "compression-br",
  "compression-gzip",
] }
