[package]
name = "evm-rpc-datasets"
edition.workspace = true
version.workspace = true

[dependencies]
alloy.workspace = true
async-stream.workspace = true
common = { path = "../../core/common" }
datasets-common = { path = "../../core/datasets-common", features = ["schemars"] }
futures.workspace = true
monitoring = { path = "../../core/monitoring" }
schemars = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
serde_with = "3.9.0"
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
fs-err.workspace = true
