[package]
name = "evm-rpc-datasets"
edition.workspace = true
version.workspace = true
license-file.workspace = true

[features]
schemars = ["dep:schemars", "datasets-common/schemars", "dep:serde_json"]

[dependencies]
alloy.workspace = true
async-stream.workspace = true
common = { path = "../../core/common" }
datasets-common = { path = "../../core/datasets-common" }
datasets-raw = { path = "../../core/datasets-raw" }
futures.workspace = true
monitoring = { path = "../../core/monitoring" }
schemars = { workspace = true, optional = true }
serde.workspace = true
serde_json = { workspace = true, optional = true }
serde_with = "3.9.0"
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
