[snowflake_demo]
vendor = "snowflake"
account = "TTBCCLZ-PUB64869"
username = "JOHNSWAN"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "AMP_DTCC_BRONZE"
schema = "PUBLIC"
table = "TRANSACTIONS"
ingest_writer_concurrency = 2
ingest_upload_concurrency = 4
ingest_copy_concurrency = 2
ingest_target_file_size = 10