[profile.default]
src = "src"
out = "out"
libs = ["lib"]
dynamic_test_linking = true  # Enable for faster compilation
via_ir = true
optimizer = true
optimizer_runs = 200

[lint]
ignore = [
    "src/*Verifier.sol",
]

[fmt]
ignore = [
    "src/*Verifier.sol",
]
