apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    repo: amp-infra
    team: infrastructure
    environment: staging
  name: amp-server
  namespace: argocd
spec:
  destination:
    namespace: amp-server
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: k8s/staging/amp-server
    repoURL: git@github.com:edgeandnode/amp-infra.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
