resources:
  - ../../base/amp-server

images:
  - name: AMP_SERVER_IMAGE_NAME
    newName: ghcr.io/edgeandnode/amp
    newTag: sha-4358a38

labels:
  - pairs:
      app: amp-server
      repo: amp-infra
      team: infrastructure
      environment: staging
    includeSelectors: true
    includeTemplates: true
