resources:
  - ../../base/amp-server

labels:
  - pairs:
      app: amp-server
      repo: amp-private
      team: amp
      environment: staging
    includeSelectors: true
    includeTemplates: true
