apiVersion: apps/v1
kind: Deployment
metadata:
  name: amp
spec:
  template:
    spec:
      containers:
        - name: server
          image: ghcr.io/edgeandnode/amp:latest # This is just a placeholder, the image is set by the ArgoCD app
          command: ["/ampd", "server"]
          ports:
            - name: flight
              containerPort: 1602
            - name: jsonl
              containerPort: 1603
            - name: registry
              containerPort: 1611
          env:
            - name: AMP_CONFIG
              value: /config/config.toml
            - name: AMP_CONFIG_DATA_DIR
              valueFrom:
                secretKeyRef:
                  name: config-secrets-server
                  key: data_dir
            - name: AMP_CONFIG_PROVIDERS_DIR
              valueFrom:
                secretKeyRef:
                  name: config-secrets-server
                  key: providers_dir
            - name: AMP_CONFIG_DATASET_DEFS_DIR
              valueFrom:
                secretKeyRef:
                  name: config-secrets-server
                  key: dataset_defs_dir
            - name: AMP_CONFIG_METADATA_DB_URL
              valueFrom:
                secretKeyRef:
                  name: config-secrets-server
                  key: db_url
