[package]
name = "verification"
edition.workspace = true
version.workspace = true
license-file.workspace = true

[dependencies]
alloy.workspace = true
amp-client = { path = "../../clients/flight" }
anyhow.workspace = true
arrow-flight.workspace = true
clap.workspace = true
futures.workspace = true
indicatif.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tonic.workspace = true
typed-arrow.workspace = true
