name: commit-check
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:

  dco:
    if: ${{ !startsWith(github.head_ref, 'renovate/') }}
    runs-on: ubuntu-latest
    # SECURITY: # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
    permissions: read-all
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.14'

      - name: dco check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DCO_CHECK_EXCLUDE_PATTERN: (dependabot|github-actions)\[bot\]@users\.noreply\.github\.com
          DCO_CHECK_VERBOSE: '1'
        run: |
          pip install -U dco-check
          dco-check
