# Build, push to GCR and deploy to Cloud Run on every PR
name: GCR Image and Cloud Run Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
        default: staging
        description: The environment to deploy to
  # pull_request:
  # push:
  #   branches: [main]
  #   tags: [v*]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  REGION: us-central1
  PROJECT_NAME: amp
  CGP_PROJECT_ID_SUFFIX: 472411

jobs:
  build_and_push:
    permissions:
      contents: read
      id-token: write

    name: Build and push to GCR
    runs-on: nscloud-ubuntu-22.04-amd64-32x32

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        id: checkout
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'

      - name: Configure Image Name and GCR Registry
        if: steps.checkout.outcome == 'success'
        id: registry
        run: |
          REPO_BASE_NAME=`basename ${{ github.repository }}`
          REGISTRY=${{ env.REGION }}-docker.pkg.dev
          REGISTRY_PATH="${REGISTRY}/${{ env.PROJECT_NAME }}-${{ inputs.environment }}-${{ env.CGP_PROJECT_ID_SUFFIX }}/${{ env.PROJECT_NAME }}"
          echo "registry=${REGISTRY}" >> $GITHUB_OUTPUT
          echo "image_name=${REGISTRY_PATH}/${REPO_BASE_NAME}" >> $GITHUB_OUTPUT
        shell: bash

      # Cache Rust dependencies
      - name: Cache Rust dependencies
        if: steps.checkout.outcome == 'success'
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/
          key: ${{ runner.os }}-cargo-${{ github.head_ref || github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # # Authenticate to Production GCP only from main branch
      # - name: Google auth to Production GCP
      #   if: github.ref == 'refs/heads/main' && inputs.environment == 'production'
      #   id: auth
      #   uses: google-github-actions/auth@b7593ed2efd1c1617e1b0254da33b86225adb2a5 # v2
      #   with:
      #     project_id: 'amp-production'
      #     workload_identity_provider: 'projects/amp-staging/locations/global/workloadIdentityPools/github-pipeline/providers/github-pipeline'

      # Authenticate to GCP based on environment
      # This will need to change if we want to deploy to production using this PR
      - name: Google auth to GCP
        if: steps.checkout.outcome == 'success'
        id: auth
        uses: google-github-actions/auth@b7593ed2efd1c1617e1b0254da33b86225adb2a5 # v2
        with:
          token_format: access_token
          project_id: "${{ env.PROJECT_NAME }}-${{ inputs.environment }}-${{ env.CGP_PROJECT_ID_SUFFIX }}"
          workload_identity_provider: ${{ inputs.environment == 'production' && secrets.AMP_PRODUCTION_WORKLOAD_IDENTITY_PROVIDER || secrets.AMP_STAGING_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ inputs.environment == 'production' && secrets.AMP_PRODUCTION_SERVICE_ACCOUNT_EMAIL || secrets.AMP_STAGING_SERVICE_ACCOUNT_EMAIL }}
          export_environment_variables: true
          create_credentials_file: true
          # request_reason: '${{ env.PROJECT_NAME}} build and push to GCR' # this will add X-Goog-Request-Reason for audit logs

      - name: Set up Cloud SDK
        if: steps.auth.outcome == 'success'
        uses: google-github-actions/setup-gcloud@26f734c2779b00b7dda794207734c511110a4368 # v3
        with:
          version: ">= 363.0.0"

      - name: Docker Auth
        if: steps.auth.outcome == 'success'
        id: docker-auth
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ${{ steps.registry.outputs.registry}}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Docker meta
        if: steps.auth.outcome == 'success'
        id: metadata
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          images: ${{ steps.registry.outputs.image_name }}
          tags: |
            type=ref,event=tag
            type=sha,format=short

      - name: Set up QEMU
        if: steps.auth.outcome == 'success'
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3
      - name: Set up Docker Buildx  
        if: steps.auth.outcome == 'success'
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
      - name: Build and push Docker image
        if: steps.auth.outcome == 'success'
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: mode=max
          sbom: true

      - name: Deploy to Cloud Run
        if: steps.auth.outcome == 'success'
        uses: google-github-actions/deploy-cloudrun@251330ba9a8a34bfbc1622895f42e1d53fd14522 # v2
        with:
          project_id: ${{ env.PROJECT_NAME }}-${{ inputs.environment }}-${{ env.CGP_PROJECT_ID_SUFFIX }}
          service: ${{ env.PROJECT_NAME }}-${{ inputs.environment }}
          image: ${{ steps.metadata.outputs.tags }}
          region: ${{ env.REGION }}

      # - name: Deploy to Production Cloud Run
      #   if: steps.auth.outcome == 'success'
      #   uses: google-github-actions/deploy-cloudrun@v2
      #   with:
      #     service: ${{ env.CLOUD_RUN_SERVICE }}
      #     image: ${{ steps.registry.outputs.image_name }}:${{ steps.metadata.outputs.tags }}
      #     region: ${{ env.REGION }}
      #     project_id: ${{ env.REPO_NAME }}-${{ inputs.environment }}
