# Build, push to GCR and deploy to Cloud Run on every PR
name: PR GCR Image and Cloud Run Deployment

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  REGION: us-central1
  CLOUD_RUN_SERVICE: nozzle-staging
  GH_IMAGE: nozzle

jobs:
  build_and_push:
    permissions:
      contents: read

    name: Build and push to GCR
    runs-on: nscloud-ubuntu-22.04-amd64-32x32

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Google auth
        id: auth
        uses: google-github-actions/auth@b7593ed2efd1c1617e1b0254da33b86225adb2a5 # v2
        with:
          credentials_json: ${{ secrets.STAGING_GOOGLE_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@26f734c2779b00b7dda794207734c511110a4368 # v3
        with:
          version: '>= 363.0.0'

      - name: Docker Auth
        id: docker-auth
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ${{ env.REGION }}-docker.pkg.dev'
      - name: Docker meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        id: metadata
        with:
          images: ${{ env.REGION }}-docker.pkg.dev/${{ github.repository }}/${{ env.GH_IMAGE }}
          tags: |
            type=ref,event=tag
            type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        id: push
        with:
          context: .
          pull: true
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true
          sbom: true

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.CLOUD_RUN_SERVICE }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ github.repository }}/${{ env.GH_IMAGE }}:${{ steps.metadata.outputs.tags }}
          region: ${{ env.REGION }}
          project_id: ${{ secrets.STAGING_GCP_NOZZLE_PROJECT_ID }}
