# Build, push to GCR and deploy to Cloud Run on every PR
name: PR GCR Image and Cloud Run Deployment

on:
  workflow_dispatch:
  pull_request:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  REGION: us-central1
  GH_ORG: edgeandnode
  GH_REPO: nozzle
  GH_IMAGE: nozzle
  CLOUD_RUN_SERVICE: nozzle-staging

jobs:
  build_and_push:
    permissions:
      contents: read
      id-token: write

    name: Build and push to GCR
    runs-on: nscloud-ubuntu-22.04-amd64-32x32

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Google auth
        id: auth
        uses: google-github-actions/auth@b7593ed2efd1c1617e1b0254da33b86225adb2a5 # v2
        with:
          credentials_json: ${{ secrets.STAGING_GOOGLE_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@26f734c2779b00b7dda794207734c511110a4368 # v3
        with:
          version: '>= 363.0.0'

      - name: Docker Auth
        id: docker-auth
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ${{ env.REGION }}-docker.pkg.dev'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Docker meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5
        id: metadata
        with:
          images: ${{ env.REGION }}-docker.pkg.dev/${{ env.GH_ORG }}/${{ env.GH_REPO }}/${{ env.GH_IMAGE }}
          tags: |
            type=ref,event=tag
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        id: push
        with:
          context: .
          pull: true
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.CLOUD_RUN_SERVICE }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.GH_ORG }}/${{ env.GH_REPO }}/${{ env.GH_IMAGE }}:${{ steps.metadata.outputs.tags }}
          region: ${{ env.REGION }}
          project_id: ${{ secrets.STAGING_GCP_NOZZLE_PROJECT_ID }}
