[package]
name = "common"
edition.workspace = true
version.workspace = true
license-file.workspace = true

[features]
# JSON Schema generation support for configuration types
schemars = ["dep:schemars"]

[dependencies]
alloy.workspace = true
amp-data-store = { path = "../data-store" }
amp-datasets-registry = { path = "../datasets-registry" }
amp-providers-registry = { path = "../providers-registry" }
arrow.workspace = true
async-stream.workspace = true
async-trait.workspace = true
bigdecimal = "0.4"
bytes.workspace = true
chrono.workspace = true
datafusion.workspace = true
datafusion-datasource.workspace = true
datafusion-tracing.workspace = true
datasets-common = { path = "../datasets-common" }
datasets-derived = { path = "../datasets-derived" }
datasets-raw = { path = "../datasets-raw" }
evm-rpc-datasets = { path = "../../extractors/evm-rpc" }
firehose-datasets = { path = "../../extractors/firehose" }
futures.workspace = true
itertools.workspace = true
js-runtime = { path = "../js-runtime" }
metadata-db = { path = "../metadata-db" }
monitoring = { path = "../monitoring" }
object_store.workspace = true
parking_lot = "0.12.4"
rand.workspace = true
regex.workspace = true
schemars = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
solana-datasets = { path = "../../extractors/solana" }
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
chrono.workspace = true
