[package]
name = "common"
edition.workspace = true
version.workspace = true

[features]
schemars = ["dep:schemars", "datasets-common/schemars"]

[dependencies]
alloy.workspace = true
async-trait.workspace = true
async-stream.workspace = true
axum.workspace = true
backon.workspace = true
bincode.workspace = true
bytes.workspace = true
datafusion.workspace = true
datafusion-proto.workspace = true
datafusion-tracing.workspace = true
datasets-common = { path = "../datasets-common" }
figment.workspace = true
foyer = "0.18"
fs-err.workspace = true
futures.workspace = true
governor.workspace = true
indoc.workspace = true
itertools.workspace = true
js-runtime = { path = "../js-runtime" }
metadata-db = { path = "../metadata-db", features = ["temp-db"] }
object_store.workspace = true
regex.workspace = true
schemars = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
stable-hash = { git = "https://github.com/graphprotocol/stable-hash" }
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
toml.workspace = true
tower.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true
datasets-derived = { version = "0.1.0", path = "../datasets-derived" }

[dev-dependencies]
chrono.workspace = true
rand.workspace = true
tempfile.workspace = true
